### PR TITLE
Added english theme deck files

### LINKED ISSUE #87: Dataset for theme decks
I'm using this API for a project I'm working on and was looking for a way to also track the theme decks. I've started building the dataset myself, figured I'd post here and see if there's any interest in it being PR'd when I'm done. No idea when that will be though.

The data model I'm using looks roughly like this - open to feedback and any information others might also want to see. The id naming convention is also open to change, I just picked something unique.

```json
[
    {
        "id": "d-base1-1",
        "name": "Overgrowth",
        "cards": [
            { "id": "base1-44", "count": 4 },
            { "id": "base1-30", "count": 2 },
            { "id": "base1-69", "count": 4 },
            { "id": "base1-33", "count": 2 },
            { "id": "base1-17", "count": 1 },
            { "id": "base1-65", "count": 4 },
            { "id": "base1-64", "count": 3 },
            { "id": "base1-35", "count": 2 },
            { "id": "base1-6", "count": 1 },
            { "id": "base1-91", "count": 2 },
            { "id": "base1-93", "count": 2 },
            { "id": "base1-94", "count": 1 },
            { "id": "base1-90", "count": 2 },
            { "id": "base1-95", "count": 2 },
            { "id": "base1-99", "count": 16 },
            { "id": "base1-102", "count": 12 }
        ]
    }
]
```

### PR DESCRIPTION
**Pull request by Monbrey**
Closes #87 

I wrote a script which extracted and parsed the HTML data from the Bulbagarden pages for theme decks and ran some validator functions against the API.

I'm about 98% confident in the accuracy of the mapping of this data to the API - I could be more accurate but that would require a lot of API spam in validating cards.

### CODE REVIEW

**Comment by adback03** [comment]
Awesome! I'm sure it is close enough. We can always fix issues if any arise. I do have one minor ask - could you title-case the types? This would be more consistent with the rest of the data.

So `Water` instead of `water`.

Sorry for the hassle!

**Comment by Monbrey** [comment]
No worries, easy script to run. Types have been title-cased.

**Comment by dlawregiets** [comment]
I hate to hijack this, but @Monbrey could you post the script that you wrote to scrape the data somewhere? I would like to get the Unified Minds and Cosmic Eclipse decks added.

**Comment by Monbrey** [comment]
> I hate to hijack this, but @Monbrey could you post the script that you wrote to scrape the data somewhere? I would like to get the Unified Minds and Cosmic Eclipse decks added.

Sorry, looks like I totally missed this. I've uploaded the scraper here: https://github.com/Monbrey/pokemon-tcg-data-scraper

The actual run method has been commented out since at the time I last used it, it wasn't doing full scraping. Hopefully the function names make sense - to get specific decks you can use `getDeck(bulbapedia_page_url)` rather than the functions for fetching and extracting all decks.

**Pull request merged**
