### PR TITLE
Added missing cards & corrected some errors

### PR DESCRIPTION
**Pull request by r0adkll**
Fixed typos in Crimson Invasion Secret Rares.
Added missing Yellow A Alternate Art cards to various sets (see: https://bulbapedia.bulbagarden.net/wiki/Yellow_A_Alternate_cards_(TCG))
Added Crobat BREAK to XYP set

### CODE REVIEW

**Comment by adback03** [comment]
Do you know of anywhere that has the images for the Yellow A cards?

**Comment by r0adkll** [comment]
I know that they are in the game. Pokellector.com has most of them I think (i.e. http://pod.pokellector.com/cards/188/N.FCO.105.18608.mobile.jpg) I'll keep looking around

**Comment by adback03** [comment]
I've been able to extract all the images, so don't worry about looking into it!

**Comment by r0adkll** [comment]
Fantastic!!

**Pull request merged**
