### PR TITLE
swshp: updated legalities, added missing cards, regulationMark of swshp-SWSH296

### PR DESCRIPTION
**Pull request by Cealgair**

### CODE REVIEW

**Comment by Cealgair** [comment]
I noticed that SWSH285 and SWSH286 are not on this repo but are in the api, so I won't add them here

**Comment by Cealgair** [comment]
I noticed that SWSH292 and SWSH293 will release on May 5. Since usually cards are not added to the api before their release, I won't add them here

**Comment by Cealgair** [comment]
Bulbapedia says SWSH299 was included in the "Jirachi V Box", but I am not sure whether it actually released, so I won't add it here

**Comment by Cealgair** [comment]
> I noticed that SWSH292 and SWSH293 will release on May 5. Since usually cards are not added to the api before their release, I won't add them here

Same story with SWSH306 and SWSH307, which will release on June 9

**Comment by Cealgair** [comment]
I didn't put "standard": "Legal" for SWSH075. It has the D regulation mark, so it's not legal anymore. Most cards with that regulation mark are considered standard Legal by the api at the moment.

**Comment by Cealgair** [comment]
> Bulbapedia says SWSH299 was included in the "Jirachi V Box", but I am not sure whether it actually released, so I won't add it here

It is also unclear to me whether SWSH303, SWSH304 and SWSH305 have released, so I won't add them either

**Comment by Cealgair** [comment]
> It is also unclear to me whether SWSH303, SWSH304 and SWSH305 have released, so I won't add them either

Judging by the TCGPlayer links provided in #386 I'd say they did release, so I will add them as well

**Comment by Nirvanna21** [comment]
Good job!

**Comment by Cealgair** [comment]
> I noticed that SWSH292 and SWSH293 will release on May 5. Since usually cards are not added to the api before their release, I won't add them here

Now I added them

> I didn't put "standard": "Legal" for SWSH075. It has the D regulation mark, so it's not legal anymore. Most cards with that regulation mark are considered standard Legal by the api at the moment.

The same applies to SWSH292 and SWSH293. See issue #409

**Comment by Cealgair** [comment]
I added the regulationMark to swshp-SWSH296 in this PR because I wanted to avoid further conflicts

**Comment by Cealgair** [comment]
> I added the regulationMark to swshp-SWSH296 in this PR because I wanted to avoid further conflicts

I updated the legalities here for the same reason. See issue #417

**Comment by Cealgair** [comment]
> Same story with SWSH306 and SWSH307, which will release on June 9

Now I've added them. I also updated the totals in sets/en.json. I chose 307 for the printedTotal because SWSH307 is the highest number, and 304 for the total because there are 302 cards in the json, plus these two:

> I noticed that SWSH285 and SWSH286 are not on this repo but are in the api, so I won't add them here

I also noticed I forgot a couple of commas in earlier commits, and that made the json files invalid. I fixed this.

@adback03 let me know if there are any issues with this PR

**Comment by Cealgair** [comment]
At this point this closes #409 and closes #417

**Comment by lilyanne12** [comment]
> I noticed that SWSH285 and SWSH286 are not on this repo but are in the api, so I won't add them here

@Cealgair Apologies for my ignorance but why would these not be included on this repo if they are in the API? Many thanks for all the work you are doing to keep this all up to date - it's amazing!

**Comment by Cealgair** [comment]
As far as I understand, the api takes data from some database that *in theory* should be always in sync with this repo. In practice, sometimes they are not in sync

**Pull request merged**
