### PR TITLE
Added MCD 2014

### PR DESCRIPTION
**Pull request by MatiasOETamminen**
Hello! You mentioned you could use some help with the MCD collections in issue #183. Here's MCD 2014. I don't have any pictures, but the picture URLs should follow the conventions.

### CODE REVIEW

**Comment by adback03** [comment]
Thanks, I just need to track down some photos and this looks good.

**Comment by MatiasOETamminen** [comment]
JP | pkmncards.com mentioned that he has the raw images for MCD2014 over at the Discord channel.

**Comment by lfgcampos** [comment]
@adback03 btw, this is not working: https://pokemontcg.io/cards?setCode=mcd14
similar to other McDonald's collections!

**Comment by adback03** [comment]
@lfgcampos I still have to publish the set to the API. I'll mark a release once it's in the API

**Pull request merged**
